#!/bin/sh
# Generate .github/CODEOWNERS from governance/policy/protected-paths. Never hand-edit
# CODEOWNERS — regenerate it: ./governance/harness/generate-codeowners.sh
set -eu

root=$(git rev-parse --show-toplevel 2>/dev/null || pwd)
policy="$root/governance/policy/protected-paths"
out="$root/.github/CODEOWNERS"

trim() { printf '%s' "$1" | sed 's/^[[:space:]]*//; s/[[:space:]]*$//'; }

{
  echo "# DO NOT EDIT — generated by governance/harness/generate-codeowners.sh from governance/policy/protected-paths."
  echo "# Regenerate after changing the policy:  ./governance/harness/generate-codeowners.sh"
  echo "# Owners review changes to these paths; enforced as a merge gate once the"
  echo "# branch ruleset requires code-owner review (see governance/README.md)."
  echo
  grep -v -e '^[[:space:]]*#' -e '^[[:space:]]*$' "$policy" | while IFS='|' read -r glob owner _reason; do
    glob=$(trim "$glob")
    owner=$(trim "$owner")
    [ -z "$glob" ] && continue
    printf '%s %s\n' "$glob" "$owner"
  done
} > "$out"

echo "Wrote $out"
