// <auto-generated/> AddPoints handler (provider = Bucket) — emitted by the provider probe.
// Scaffold body substituted from the `mutate` snippet; verbs + receiver from the StoreCatalog.
#nullable enable
using Probe;
using Probe.Domain;

namespace Emitted;

public static class AddPointsBucketHandler
{
    public static User Handle(Bucket<User> bucket, AddPointsCommand command)
    {
        var __key = new BucketKey(command.Region);
        var agg = bucket.Download(__key);
        agg.AddPoints(command.Points);
        bucket.Upload(__key, agg);
        return agg;
    }
}
