// <auto-generated/>
#nullable enable
namespace Spike;

static partial class Recipe
{
    public static Expr<int> Add(Expr<int> a, Expr<int> b) => new AddNode(a, b);
    public static IStmt Assign(Var<int> target, Expr<int> value) => new AssignNode(target, value);
    public static IStmt Define(Expr<int> value, Var<int> @var) => new DefineNode(value, @var);
    public static IStmt IfElse(Expr<bool> condition, Block then, Block @else) => new IfElseNode(condition, then, @else);
    public static Expr<bool> LessThan(Expr<int> a, Expr<int> b) => new LessThanNode(a, b);
    public static IStmt Loop(Expr<int> count, Var<int> i, Block body) => new LoopNode(count, i, body);
    public static IStmt Return(Expr<int> value) => new ReturnNode(value);
}
