// <auto-generated/>
#nullable enable
namespace Spike;

sealed record AddNode(IExpr<int> A, IExpr<int> B) : IExpr<int>;
sealed record AssignNode(Var<int> Target, IExpr<int> Value) : IStmt;
sealed record DefineNode(IExpr<int> Value, Var<int> Var) : IStmt;
sealed record IfElseNode(IExpr<bool> Condition, Block Then, Block Else) : IStmt;
sealed record LessThanNode(IExpr<int> A, IExpr<int> B) : IExpr<bool>;
sealed record LoopNode(IExpr<int> Count, Var<int> I, Block Body) : IStmt;
sealed record ReturnNode(IExpr<int> Value) : IStmt;
