// <auto-generated/>
#nullable enable
namespace Spike;

sealed record AddNode(Expr<int> A, Expr<int> B) : Expr<int>;
sealed record AssignNode(Var<int> Target, Expr<int> Value) : Stmt;
sealed record DefineNode(Var<int> Var, Expr<int> Value) : Stmt;
sealed record IfElseNode(Expr<bool> Condition, Block Then, Block Else) : Stmt;
sealed record LessThanNode(Expr<int> A, Expr<int> B) : Expr<bool>;
sealed record LoopNode(Var<int> I, Expr<int> Count, Block Body) : Stmt;
sealed record ReturnNode(Expr<int> Value) : Stmt;
