// <auto-generated/>
#nullable enable
namespace Spike;

sealed record AddNode(Expr<int> A, Expr<int> B) : Expr<int>;
sealed record AssignNode(Var<int> Target, Expr<int> Value) : IStmt;
sealed record DefineNode(Expr<int> Value, Var<int> Var) : IStmt;
sealed record IfElseNode(Expr<bool> Condition, Block Then, Block Else) : IStmt;
sealed record LessThanNode(Expr<int> A, Expr<int> B) : Expr<bool>;
sealed record LoopNode(Expr<int> Count, Var<int> I, Block Body) : IStmt;
sealed record ReturnNode(Expr<int> Value) : IStmt;
