#!/usr/bin/env python3
"""Derived views over a block-structured doc — generated, never authored.

Because the engine parses blocks (singletons + grouped collections), it can
produce read-only views for free: an index (id / group / type / title / status)
and a phase status board.

    python3 outline.py out/git-feature.plan.md            # print views
    python3 outline.py out/git-feature.plan.md --write     # inject the index
                                                            # between INDEX markers
"""
import sys, os, re
from validate import parse, load_blocks, doctype_of

ROOT = os.path.dirname(os.path.abspath(__file__))
START = "<!-- INDEX:START (generated by outline.py — do not edit) -->"
END = "<!-- INDEX:END -->"


def index_md(blocks):
    rows = ["**Outline** (generated — run `outline.py --write`)", "",
            "| id | group | type | title | status |",
            "| --- | --- | --- | --- | --- |"]
    for b in blocks:
        rows.append(f"| {b['id']} | {b['group'] or ''} | {b['type']} "
                    f"| {b['title']} | {b['attrs'].get('status', '')} |")
    return "\n".join(rows)


def status_board(blocks):
    phases = [b for b in blocks if b["type"] == "phase"]
    if not phases:
        return ""
    out = ["", "Phase status board:"]
    for st in ["doing", "blocked", "todo", "done"]:
        named = [f"{b['id']}:{b['title']}" for b in phases if b["attrs"].get("status") == st]
        if named:
            out.append(f"  {st:8} {'  '.join(named)}")
    return "\n".join(out)


def main():
    if len(sys.argv) < 2:
        raise SystemExit("usage: outline.py <plan.md> [--write]")
    path = sys.argv[1]
    write = "--write" in sys.argv[2:]
    lines = open(path).readlines()
    doctype_of(path, lines)
    defs = load_blocks()
    blocks, _ = parse(lines, defs)
    idx = index_md(blocks)

    if write:
        src = open(path).read()
        block = f"{START}\n{idx}\n{END}"
        if START in src:
            src = re.sub(re.escape(START) + r".*?" + re.escape(END), block, src, flags=re.S)
        else:
            at = src.find("\n## ")
            src = src[:at] + "\n\n" + block + "\n" + src[at:]
        open(path, "w").write(src)
        print(f"injected index ({len(blocks)} blocks) into {os.path.relpath(path, ROOT)}")
        return

    print(idx)
    print(status_board(blocks))


if __name__ == "__main__":
    main()
