// <auto-generated/> AddPoints handler (provider = Repo) — emitted by the provider probe.
// Load/save DERIVED from the provider's Lowering; body LIFTED from the recipe (provider-agnostic).
#nullable enable
using Probe;
using Probe.Domain;

namespace Emitted;

public static class AddPointsRepoHandler
{
    public static User Handle(Repo<User> repo, AddPointsCommand command)
    {
        var __key = command.Email;
        var agg = repo.Load(__key);
        agg.AddPoints(command.Points);
        repo.Store(__key, agg);
        return agg;
    }
}
