// <auto-generated/> AddPoints handler (BucketStore) — emitted by the provider probe.
// Body substituted from the `mutate` snippet; the store SURVIVES (store.Get/Save), swapped by its fill.
#nullable enable
using Probe;
using Probe.Domain;

namespace Emitted;

public static class AddPointsBucketStoreHandler
{
    public static User Handle(AddPointsCommand command)
    {
        var store = Stores.BucketStore<User>();
        var key = new BucketKey(command.Region);
        var agg = store.Get(key);
        agg.AddPoints(command.Points);
        store.Save(key, agg);
        return agg;
    }
}
