using RemoteAgents.Primitives;

namespace RemoteAgents.Tests.Primitives;

public class GitOpsTests
{
    [Fact]
    public async Task PushAsync_force_to_main_is_refused()
    {
        var req = new GitPushRequest(ProjectDir: ".", Branch: "main", Force: true);
        await Assert.ThrowsAsync<InvalidOperationException>(async () =>
            await GitOps.PushAsync(req));
    }

    [Fact]
    public async Task PushAsync_force_to_master_is_refused()
    {
        var req = new GitPushRequest(ProjectDir: ".", Branch: "master", Force: true);
        await Assert.ThrowsAsync<InvalidOperationException>(async () =>
            await GitOps.PushAsync(req));
    }

    [Fact]
    public async Task AddAsync_with_empty_files_throws()
    {
        var req = new GitAddRequest(ProjectDir: ".", Files: Array.Empty<string>());
        await Assert.ThrowsAsync<ArgumentException>(async () =>
            await GitOps.AddAsync(req));
    }

    [Fact]
    public async Task CommitAsync_with_empty_message_throws()
    {
        var req = new GitCommitRequest(ProjectDir: ".", Message: "");
        await Assert.ThrowsAsync<ArgumentException>(async () =>
            await GitOps.CommitAsync(req));
    }

    // Integration: real git in a temp repo. Skipped if git is not on PATH.

    [Fact]
    public async Task ChangedFilesAsync_reports_modified_added_untracked()
    {
        using var repo = await TempGitRepo.CreateAsync();
        await repo.WriteAsync("a.txt", "hello");
        await repo.WriteAsync("b.txt", "world");
        await repo.CommitAllAsync("init");

        // modify a.txt; create untracked c.txt
        await repo.WriteAsync("a.txt", "changed");
        await repo.WriteAsync("c.txt", "new");

        var files = await GitOps.ChangedFilesAsync(repo.Path);
        Assert.Contains("a.txt", files);
        Assert.Contains("c.txt", files);
        Assert.Equal(2, files.Count);
    }

    [Fact]
    public async Task RestoreUnstagedExceptAsync_keeps_protected_reverts_rest()
    {
        using var repo = await TempGitRepo.CreateAsync();
        await repo.WriteAsync("keep.cs", "original");
        await repo.WriteAsync("noise.txt", "original");
        await repo.CommitAllAsync("init");

        // Claude touched keep.cs. Validator noisily modified noise.txt and
        // created an untracked .meta file.
        await repo.WriteAsync("keep.cs", "edited by claude");
        await repo.WriteAsync("noise.txt", "edited by validator");
        await repo.WriteAsync("artifact.meta", "generated by validator");

        var reverted = await GitOps.RestoreUnstagedExceptAsync(
            repo.Path,
            new[] { "keep.cs" });

        Assert.Contains("noise.txt", reverted);
        Assert.Contains("artifact.meta", reverted);
        Assert.DoesNotContain("keep.cs", reverted);

        Assert.Equal("edited by claude", await repo.ReadAsync("keep.cs"));
        Assert.Equal("original", await repo.ReadAsync("noise.txt"));
        Assert.False(File.Exists(Path.Combine(repo.Path, "artifact.meta")));
    }

    [Fact]
    public async Task ChangedFilesAsync_stable_after_checkout_dash_dash()
    {
        // Regression: FsDiff would still see noise.txt as changed because
        // git checkout bumps mtime. ChangedFilesAsync must not.
        using var repo = await TempGitRepo.CreateAsync();
        await repo.WriteAsync("a.txt", "v1");
        await repo.CommitAllAsync("init");

        await repo.WriteAsync("a.txt", "v2");
        await RunCommand.RunAsync("git checkout -- a.txt",
            new RunCommandOptions(Cwd: repo.Path));

        var files = await GitOps.ChangedFilesAsync(repo.Path);
        Assert.Empty(files);
    }
}

// Tiny throwaway-git-repo helper. `git init`, an initial author/email
// scoped to the repo, and a working tree under %TEMP%/ra-git-<guid>.
internal sealed class TempGitRepo : IAsyncDisposable, IDisposable
{
    public string Path { get; }
    private TempGitRepo(string path) { Path = path; }

    public static async Task<TempGitRepo> CreateAsync()
    {
        var dir = System.IO.Path.Combine(System.IO.Path.GetTempPath(), "ra-git-" + Guid.NewGuid().ToString("N"));
        Directory.CreateDirectory(dir);
        var repo = new TempGitRepo(dir);
        await Run("git init -q");
        // Scope identity to the repo so we never touch global config.
        await Run("git config user.email tests@example.com");
        await Run("git config user.name tests");
        return repo;

        async Task Run(string cmd)
        {
            var r = await RunCommand.RunAsync(cmd, new RunCommandOptions(Cwd: dir));
            if (r.ExitCode != 0)
                throw new InvalidOperationException($"TempGitRepo setup failed: {cmd} -> {r.Stderr}");
        }
    }

    public Task WriteAsync(string rel, string contents)
        => File.WriteAllTextAsync(System.IO.Path.Combine(Path, rel), contents);

    public Task<string> ReadAsync(string rel)
        => File.ReadAllTextAsync(System.IO.Path.Combine(Path, rel));

    public async Task CommitAllAsync(string message)
    {
        var add = await RunCommand.RunAsync("git add -A", new RunCommandOptions(Cwd: Path));
        if (add.ExitCode != 0) throw new InvalidOperationException($"git add failed: {add.Stderr}");
        var commit = await RunCommand.RunAsync($"git commit -q -m \"{message}\"", new RunCommandOptions(Cwd: Path));
        if (commit.ExitCode != 0) throw new InvalidOperationException($"git commit failed: {commit.Stderr}");
    }

    public void Dispose()
    {
        try { Directory.Delete(Path, recursive: true); } catch { }
    }

    public ValueTask DisposeAsync()
    {
        Dispose();
        return ValueTask.CompletedTask;
    }
}
