using System.Text.RegularExpressions;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp;
using Microsoft.CodeAnalysis.CSharp.Syntax;

namespace Probe;

// Lower a recipe to an owned handler by SUBSTITUTING the `mutate` snippet — the same
// mechanism as the original spike's Loop -> for. The scaffold body (load -> body -> save ->
// return) ORIGINATES from real, compiler-checked C# in Snippets.cs; the emitter only fills
// its holes and rewrites the canonical verbs to the provider's idiomatic methods. It does
// NOT string-build the scaffold. (The outer class/method frame is still assembled — that is
// the builder's job; snippet-ising the frame is a later step.)
static class Emitter
{
    public readonly record struct Artifact(string RelativePath, string Text);

    static readonly Regex BlockCall = new(@"Block\s*\.\s*Of\s*\(\s*""(\w+)""\s*\)\s*;");

    public static Artifact Lower(Lift.Recipe recipe)
    {
        var provider = StoreCatalog.Resolve(recipe.StoreFactory);
        var body = RenderMutate(recipe, provider);

        var cls = $"{recipe.FeatureName}{provider.Tag}Handler";
        var full = $$"""
            // <auto-generated/> {{recipe.FeatureName}} handler (provider = {{provider.Tag}}) — emitted by the provider probe.
            // Scaffold body substituted from the `mutate` snippet; verbs + receiver from the StoreCatalog.
            #nullable enable
            using Probe;
            using Probe.Domain;

            namespace Emitted;

            public static class {{cls}}
            {
                public static {{recipe.Aggregate}} Handle({{provider.ParamType(recipe.Aggregate)}} {{provider.Receiver}}, {{recipe.Command}} command)
                {
            {{Indent(body, 8)}}
                }
            }
            """;

        return new Artifact($"{recipe.FeatureName}.{provider.Tag}.Handler.cs", Normalize(full));
    }

    // Parse the `mutate` snippet, fill its holes, rewrite Get/Save -> the provider's methods.
    static string RenderMutate(Lift.Recipe recipe, StoreCatalog.Provider provider)
    {
        var snippet = LoadSnippet("mutate");
        var rewritten = (BlockSyntax)new MutateRewriter(provider.Receiver, recipe.KeyExpression, provider.VerbMap)
            .Visit(snippet.Body!)!;

        var lines = rewritten.Statements.Select(s => s.NormalizeWhitespace().ToFullString());
        var text = string.Join("\n", lines);
        return BlockCall.Replace(text, m => FillBlock(m.Groups[1].Value, recipe));
    }

    static string FillBlock(string id, Lift.Recipe recipe) => id switch
    {
        "body" => string.Join("\n", recipe.BodyStatements),
        _ => throw new InvalidOperationException($"the mutate snippet has an unfilled Block.Of(\"{id}\")."),
    };

    static MethodDeclarationSyntax LoadSnippet(string name)
    {
        var root = CSharpSyntaxTree.ParseText(File.ReadAllText(Snippets.SourcePath)).GetRoot();
        foreach (var method in root.DescendantNodes().OfType<MethodDeclarationSyntax>())
        {
            var attr = method.AttributeLists.SelectMany(a => a.Attributes)
                .FirstOrDefault(a => a.Name.ToString() is "Snippet" or "SnippetAttribute");
            if (attr?.ArgumentList?.Arguments.FirstOrDefault()?.Expression is LiteralExpressionSyntax lit
                && lit.Token.ValueText == name)
                return method;
        }
        throw new InvalidOperationException($"no [Snippet(\"{name}\")] in {Snippets.SourcePath}.");
    }

    static string Indent(string text, int spaces)
    {
        var pad = new string(' ', spaces);
        return string.Join("\n", text.Replace("\r\n", "\n").Split('\n')
            .Select(l => l.Length == 0 ? l : pad + l));
    }

    static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";

    // store  (marker) -> the provider receiver name (repo / bucket)
    // key    (param)  -> the lifted key expression, at its single non-member usage
    // .Get/.Save      -> the provider's idiomatic method names (VerbMap)
    sealed class MutateRewriter(string receiver, string keyExpression, IReadOnlyDictionary<string, string> verbs)
        : CSharpSyntaxRewriter
    {
        public override SyntaxNode? VisitIdentifierName(IdentifierNameSyntax node)
        {
            if (node.Identifier.ValueText == "store")
                return SyntaxFactory.IdentifierName(receiver).WithTriviaFrom(node);
            if (node.Identifier.ValueText == "key" && node.Parent is not MemberAccessExpressionSyntax)
                return SyntaxFactory.ParseExpression(keyExpression).WithTriviaFrom(node);
            return base.VisitIdentifierName(node);
        }

        public override SyntaxNode? VisitMemberAccessExpression(MemberAccessExpressionSyntax node)
        {
            var visited = (MemberAccessExpressionSyntax)base.VisitMemberAccessExpression(node)!;
            return verbs.TryGetValue(node.Name.Identifier.ValueText, out var to)
                ? visited.WithName(SyntaxFactory.IdentifierName(to))
                : visited;
        }
    }
}
