using System.Text;

namespace Probe;

// Deterministic lowering: a Mutation (its provider Lowering + type names) + the lifted
// glue -> an owned handler. The load/save lines are DERIVED from the provider's Lowering
// (Repo -> Load/Store, Bucket -> Download/Upload), so the SAME recipe shape emits two
// different owned handlers. The key is bound ONCE to __key and threaded into both the
// provider-specific load and save.
static class Emitter
{
    public readonly record struct Artifact(string RelativePath, string Text);

    public static string AssembleBody(Mutation m, Lift.Glue glue)
    {
        var lo = m.Lowering;
        var sb = new StringBuilder();
        sb.AppendLine($"var __key = {glue.KeyExpression};");
        sb.AppendLine($"var agg = {lo.Param}.{lo.LoadMethod}(__key);");
        foreach (var stmt in glue.BodyStatements)
            foreach (var line in stmt.Replace("\r\n", "\n").TrimEnd().Split('\n'))
                sb.AppendLine(line.TrimEnd());
        sb.AppendLine($"{lo.Param}.{lo.SaveMethod}(__key, agg);");
        sb.AppendLine("return agg;");
        return sb.ToString();
    }

    public static Artifact Lower(Mutation m, Lift.Glue glue)
    {
        var lo = m.Lowering;
        var cls = $"{m.FeatureName}{lo.Tag}Handler";
        var body = AssembleBody(m, glue);

        var sb = new StringBuilder();
        sb.AppendLine($"// <auto-generated/> {m.FeatureName} handler (provider = {lo.Tag}) — emitted by the provider probe.");
        sb.AppendLine("// Load/save DERIVED from the provider's Lowering; body LIFTED from the recipe (provider-agnostic).");
        sb.AppendLine("#nullable enable");
        sb.AppendLine("using Probe;");
        sb.AppendLine("using Probe.Domain;");
        sb.AppendLine();
        sb.AppendLine("namespace Emitted;");
        sb.AppendLine();
        sb.AppendLine($"public static class {cls}");
        sb.AppendLine("{");
        sb.AppendLine($"    public static {m.Return} Handle({lo.ParamType} {lo.Param}, {m.Command} command)");
        sb.AppendLine("    {");
        foreach (var line in body.Replace("\r\n", "\n").TrimEnd().Split('\n'))
            sb.AppendLine(line.Length == 0 ? string.Empty : "        " + line.TrimEnd());
        sb.AppendLine("    }");
        sb.AppendLine("}");
        return new Artifact($"{m.FeatureName}.{lo.Tag}.Handler.cs", Normalize(sb.ToString()));
    }

    static string Normalize(string text) => text.Replace("\r\n", "\n").TrimEnd() + "\n";
}
